# pg_hba.conf — Acceso y autenticación
# TYPE  DATABASE        USER            ADDRESS                 METHOD

# Conexiones locales
local   all             all                                     trust
host    all             all             127.0.0.1/32            md5
host    all             all             ::1/128                 md5

# Replicación entre nodos del cluster
host    replication     replicator      172.20.0.0/24           md5
host    all             banco_admin     172.20.0.0/24           md5
host    all             all             0.0.0.0/0               md5

host replication replicator 0.0.0.0/0 md5
